---
- :desc: ""
  :when_not_human: "2011-05-04"
  :event_title: Dojo do GURU/RS no Encontro Locaweb
  :who: Juan Maiz / Felipe Cabral
  :event_site: http://www.gururs.org/
  :event_site_title: Agenda do evento
  :title: Dojo do GURU/RS no Encontro Locaweb
  :title_link: http://www.gururs.org/
  :where: "Porto Alegre, RS"
  :when: 04/05
- :desc: ""
  :when_not_human: "2011-01-20"
  :event_title: Campuseiros Empreendem
  :who: Pedro Axelrud
  :event_site: http://www.campus-party.com.br/2011/campuseros-empreendem.html
  :event_site_title: www.campus-party.com.br
  :title: Mailee.me na CP
  :title_link: http://www.youtube.com/watch?v=pKjJcRkGBPg&feature=player_embedded
  :where: "Centro Imigrantes, São Paulo, SP"
  :when: 20/01
- :desc: ""
  :when_not_human: "2011-01-20"
  :event_title: Campuseiros Empreendem
  :who: Daniel Weinmann
  :event_site: http://www.campus-party.com.br/2011/campuseros-empreendem.html
  :event_site_title: www.campus-party.com.br
  :title: Catarse na CP
  :title_link: http://catarse.me/
  :where: "Centro Imigrantes, São Paulo, SP"
  :when: 20/01
- :desc: ""
  :when_not_human: "2011-02-26"
  :event_title: Ruby Masters
  :who: Juan Maiz
  :event_site: http://rubymastersconf.com
  :event_site_title: rubymastersconf.com
  :title: SaaS - Software as a Service
  :title_link: http://rubymastersconf.com/
  :where: "Online"
  :when: 26/02
