---
- :desc: ""
  :when_not_human: "2011-05-23"
  :event_title: SLLConf
  :who: Juan Maiz
  :event_site: http://sllconfportoalegre.eventbrite.com/
  :event_site_title: Inscrições
  :title: Transmissão Ao Vivo da SLLConf
  :title_link: http://sllconfportoalegre.eventbrite.com/
  :where: "Porto Alegre, RS"
  :when: 23/05

- :desc: ""
  :when_not_human: "2011-05-21"
  :event_title: Dojo de Javascript
  :who: Diogo Biazus
  :event_site: http://codingdojo.tw/?p=114
  :event_site_title: Inscrições
  :title: Dojo de Javascript na Thoughtworks
  :title_link: http://codingdojo.tw/?p=114
  :where: "Porto Alegre, RS"
  :when: 21/05
 
- :desc: ""
  :when_not_human: "2011-05-04"
  :event_title: Dojo do GURU/RS
  :who: Juan Maiz / Felipe Cabral
  :event_site: http://www.gururs.org/
  :event_site_title: Agenda do evento
  :title: Dojo do GURU/RS no Encontro Locaweb
  :title_link: http://www.gururs.org/
  :where: "Porto Alegre, RS"
  :when: 04/05
